export const repos = [
  'opentensor/prompting',
  'myshell-ai/MyShell-TTS-Subnet',
  'manifold-inc/targon',
  'OpenKaito/openkaito',
  'NousResearch/finetuning-subnet',
  'eclipsevortex/SubVortex',
  'taoshidev/proprietary-trading-network', //
  'RaoFoundation/pretraining',
  'gitphantomman/d3_subnet',
  'Cazure8/transcription-subnet',
  'backend-developers-ltd/ComputeHorde',
  'RusticLuftig/data-universe',
  'synapsec-ai/llm-defender-subnet',
  // 'ceterum1/llm-defender-subnet',
  'blockchain-insights/blockchain-data-subnet',
  'eseckft/BitAds.ai',
  'CortexLM/flavia',
  'corcel-api/cortex.t',
  'namoray/vision',
  'RogueTensor/bitagent_subnet',
  'ifrit98/storage-subnet',
  'Datura-ai/smart-scrape',
  // 'surcyf123/smart-scrape',
  'NicheTensor/NicheImage',
  'omegalabsinc/omegalabs-bittensor-subnet',
  'KMFODA/DistributedTraining',
  'Supreme-Emperor-Wang/ImageAlchemy',
  'neuralinternet/compute-subnet',
  'teast21/snpOracle',
  'fractal-net/fractal',
  'womboai/wombo-bittensor-subnet',
  'nimaaghli/NASChain',
  'It-s-AI/llm-detection',
]